name: Chocolatey-AU Update

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: chocolatey-community/chocolatey-au-action@4d82e15dec9822c1e080febc9ed494a3ba708955
        with:
          package-paths: |
            automatic/*
          push: true
          api-key: ${{ secrets.CHOCO_API_KEY }}
          test-install: true
          commit-changes: true
          commit-message: 'chore: Chocolatey-AU update [skip ci]'